<a href="https://colab.research.google.com/github/AjeetCodes/BuildWithAjeet/blob/master/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [ ]:
torch.__version__

'2.8.0+cu126'

In [ ]:
if torch.cuda.is_available():
  print("GPU IS Available")
  print(f"Using GPU:{torch.cuda.get_device_name(0)}")
else:
  print("Not Found!!")

GPU IS Available
Using GPU:Tesla T4


# Creating Tensor

In [ ]:
#using empty
emptyTensor = torch.empty(2,2)
print(emptyTensor)

tensor([[3.2051e-13, 4.5307e-41],
        [3.2051e-13, 4.5307e-41]])


# Creating zeros tensor

In [ ]:
# using zeros
zerosTensor = torch.zeros(2,3, dtype=float)
zerosTensor

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

# Creating Random Tensor

In [ ]:
# using rand
randTensor = torch.rand(2,3)
randTensor.shape

torch.Size([2, 3])

# **Exercise**

## **🧠 LEVEL 1 — Basics**


### 1. **Create Different Tensors**

    * Create a 1D tensor of 10 zeros
    * Create a 2D tensor of ones with shape (3, 4)
    * Create a tensor filled with random numbers between 0 and 1

### 2. **Check Tensor Properties**

    * Print .dtype, .device, .shape
    * Move one tensor to CUDA (if available)
### 3. **Tensor Initialization**

    * Use torch.arange(), torch.linspace(), torch.eye(), and torch.randperm()
    * Example: create a tensor of even numbers from 2 to 20









# ⚙️ LEVEL 2 — Tensor Operations
**Goal:** Practice arithmetic and transformation operations


## 🔹 Element-wise Operations

**Tasks:**
- Create two tensors of shape **(3,3)**
- Perform the following element-wise operations:
  - Addition  
  - Subtraction  
  - Multiplication  
  - Division


In [ ]:
t1 = torch.arange(1, 7, 1, dtype=int)
t1 = t1.reshape(2,3)
t1

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
t2 = torch.arange(7, 13, 1, dtype=int).reshape(2,3)
t2

tensor([[ 7,  8,  9],
        [10, 11, 12]])

### **Add**

In [ ]:
add = t1+t2
add

tensor([[ 8, 10, 12],
        [14, 16, 18]])

### **Subtraction**

In [ ]:
sub = t2-t1
sub

tensor([[6, 6, 6],
        [6, 6, 6]])

### **Multiplication**

In [ ]:
mul = t1*t2
mul

tensor([[ 7, 16, 27],
        [40, 55, 72]])

### **Division**

In [ ]:
div = t2/t1
div.abs

<function Tensor.abs>

## 🔹 Matrix Operations

**Tasks:**
- Create two tensors of shape **(2,3)** and **(3,2)**
- Perform matrix multiplication using:
  - `torch.matmul`
  - or the `@` operator


## 🔹 Reshaping and Stacking

**Tasks:**
- Create a tensor of shape **(2,3)**
- Reshape it to **(3,2)**
- Stack it **3 times vertically**
- Stack it **3 times horizontally**


## 🔹 Slicing and Indexing

**Tasks:**
- Create a tensor of shape **(3,3)**
- Extract:
  - The **1st row**
  - The **2nd column**
  - A **submatrix** (for example: first 2 rows and last 2 columns)


# 🧩 LEVEL 3 — Real-world Simulation
**Goal:** Start thinking like a model builder


## 🔹 Simulate a Simple Dataset

**Tasks:**
- Create a tensor of **10 house sizes** (random values between **500–2000 sqft**)  
- Create another tensor of **house prices** using the formula:  
  \[
  \text{price} = \text{size} \times 3000 + \text{random noise}
  \]
- (Optional) Plot the relationship between **house size** and **price** using `matplotlib`


## 🔹 Mean and Standardization

**Tasks:**
- Compute the **mean** and **standard deviation** of the house sizes
- Normalize the dataset using:  
  \[
  \text{normalized} = \frac{\text{tensor} - \text{mean}}{\text{std}}
  \]


## 🔹 Simple Tensor Gradient Practice

**Tasks:**
- Create a tensor  
  \[
  x = \text{torch.tensor}([2.0], \text{requires_grad=True})
  \]
- Define  
  \[
  y = x^2 + 3x + 2
  \]
- Compute gradient using `y.backward()`
- Print the gradient value `x.grad`


# Solutions
* Create a 1D tensor of 10 zeros
* Create a 2D tensor of ones with shape (3, 4)
* Create a tensor filled with random numbers between 0 and 1

Create a 1D tensor of 10 zeros

In [ ]:
zeros_tensor = torch.zeros(10)
zeros_tensor

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Create a 2D tensor of ones with shape (3, 4)


In [ ]:
ones_array = torch.ones(3,4)
# ones_array.ndim

In [ ]:
rand_nums = torch.rand(10)
rand_nums

tensor([0.7993, 0.5261, 0.5352, 0.0758, 0.5981, 0.4864, 0.6837, 0.5893, 0.7848,
        0.9854])

## Tensor Initialization
- Use torch.arange(), torch.linspace(), torch.eye(), and torch.randperm()
- Example: create a tensor of even numbers from 2 to 20

In [ ]:
t_arange = torch.arange(2, 20, 2, dtype=int)
t_arange

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
t_linspace = torch.linspace(2, 20, 10, dtype=int)
t_linspace

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
t = torch.eye(5)
t

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

## **Auto Grad**

In [ ]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [ ]:
y = x**2 + 3*x +1
y

tensor(11., grad_fn=<AddBackward0>)

In [ ]:
y.backward()

In [ ]:
x.grad

tensor(7.)

# **Gradient Practice with Autograd (PyTorch)**

In [ ]:
# 1️⃣ Simple function f(x) = x^2
x = torch.tensor(3.0, requires_grad=True)
y = x ** 2
y.backward()
print(x.grad)  # dy/dx = 2x = 6

tensor(6.)


In [ ]:
# 2️⃣ f(x) = x^3 + 2x
x = torch.tensor(2.0, requires_grad=True)
y = x**3 + 2*x
y.backward()
print(x.grad)

tensor(14.)


In [ ]:
# 3️⃣ f(x, y) = x^2 + y^3
x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(3.0, requires_grad=True)
z = x**2 + y**3
z.backward()
print(x.grad, y.grad)

tensor(4.) tensor(27.)


##Small Optimization Practice (Gradient Descent by Hand)
 - Now let’s use gradient to minimize a function 👇

In [7]:
# Initialize w randomly
w = torch.tensor(0.0, requires_grad=True)

learning_rate = 0.1

for i in range(10):
    # Function
    loss = (w - 5)**2

    # Backprop
    loss.backward()

    print(f'learning_rate -: {learning_rate}, grad -> {w.grad}')
    # Update weight manually
    with torch.no_grad():
        w -= learning_rate * w.grad

    print(w)
    # Reset gradient
    w.grad.zero_()

    print(f"Step {i+1}: w = {w.item():.4f}, loss = {loss.item():.4f}")

learning_rate -: 0.1, grad -> -10.0
tensor(1., requires_grad=True)
Step 1: w = 1.0000, loss = 25.0000
learning_rate -: 0.1, grad -> -8.0
tensor(1.8000, requires_grad=True)
Step 2: w = 1.8000, loss = 16.0000
learning_rate -: 0.1, grad -> -6.400000095367432
tensor(2.4400, requires_grad=True)
Step 3: w = 2.4400, loss = 10.2400
learning_rate -: 0.1, grad -> -5.119999885559082
tensor(2.9520, requires_grad=True)
Step 4: w = 2.9520, loss = 6.5536
learning_rate -: 0.1, grad -> -4.095999717712402
tensor(3.3616, requires_grad=True)
Step 5: w = 3.3616, loss = 4.1943
learning_rate -: 0.1, grad -> -3.2767996788024902
tensor(3.6893, requires_grad=True)
Step 6: w = 3.6893, loss = 2.6844
learning_rate -: 0.1, grad -> -2.6214399337768555
tensor(3.9514, requires_grad=True)
Step 7: w = 3.9514, loss = 1.7180
learning_rate -: 0.1, grad -> -2.097151756286621
tensor(4.1611, requires_grad=True)
Step 8: w = 4.1611, loss = 1.0995
learning_rate -: 0.1, grad -> -1.6777210235595703
tensor(4.3289, requires_grad=Tru

In [3]:

import torch.nn as nn

# Actual and predicted values
y_true = torch.tensor([3.0, 5.0, 7.0])
y_pred = torch.tensor([2.5, 5.5, 6.0])

# Step 1: Define Loss Function
criterion = nn.MSELoss()   # Mean Squared Error

# Step 2: Compute Loss
loss = criterion(y_pred, y_true)

print("Loss value:", loss.item())


Loss value: 0.5
